-- // create_table_offre
-- Migration SQL that makes the change goes here.
CREATE TABLE OFFRE (
	OFF_ID SERIAL PRIMARY KEY,
	OFF_DATE_CREATION DATE NOT NULL,
	OFF_TITRE VARCHAR(60) NOT NULL,
	OFF_PRIX INTEGER NOT NULL,
	OFF_NOMBRE_PERSONNE INTEGER NOT NULL,
	OFF_DUREE_MINUTE INTEGER NOT NULL,
	OFF_DATE_REPAS TIMESTAMP NOT NULL,
	OFF_NOTE VARCHAR(1024),
	OFF_MENU VARCHAR(1024) NOT NULL,
	OFF_AGE_MIN INTEGER,
	OFF_AGE_MAX INTEGER,
	OFF_ANIMAUX BOOLEAN NOT NULL,
	OFF_ADR_ID INTEGER NOT NULL REFERENCES ADRESSE(ADR_ID),
	OFF_TYP_ID INTEGER NOT NULL REFERENCES TYPE_CUISINE(TYP_ID),
	OFF_USR_ID INTEGER NOT NULL REFERENCES UTILISATEUR(USR_ID)
);


-- //@UNDO
-- SQL to undo the change goes here.
DROP TABLE OFFRE;

