-- // fill_table_type_cuisine
-- Migration SQL that makes the change goes here.
INSERT INTO TYPE_CUISINE (TYP_CUISINE) VALUES ('Cuisine régionale');
INSERT INTO TYPE_CUISINE (TYP_CUISINE) VALUES ('Africaine');
INSERT INTO TYPE_CUISINE (TYP_CUISINE) VALUES ('Steak House');
INSERT INTO TYPE_CUISINE (TYP_CUISINE) VALUES ('Gastronomique');
INSERT INTO TYPE_CUISINE (TYP_CUISINE) VALUES ('Grec');
INSERT INTO TYPE_CUISINE (TYP_CUISINE) VALUES ('Asiatique');
INSERT INTO TYPE_CUISINE (TYP_CUISINE) VALUES ('Espagnole');
INSERT INTO TYPE_CUISINE (TYP_CUISINE) VALUES ('Barbecue');
INSERT INTO TYPE_CUISINE (TYP_CUISINE) VALUES ('Provencale');
INSERT INTO TYPE_CUISINE (TYP_CUISINE) VALUES ('Bretonne');
INSERT INTO TYPE_CUISINE (TYP_CUISINE) VALUES ('Italienne');
INSERT INTO TYPE_CUISINE (TYP_CUISINE) VALUES ('Savoyard');
INSERT INTO TYPE_CUISINE (TYP_CUISINE) VALUES ('Alsacienne');
INSERT INTO TYPE_CUISINE (TYP_CUISINE) VALUES ('Mexicaine');


-- //@UNDO
-- SQL to undo the change goes here.
DELETE FROM TYPE_CUISINE WHERE TYP_ID BETWEEN 1 AND 14;

